(function($,Site){var util={getReqUri:function(opts){return $.param(opts);},empty:function(mixed_var){var key,i,len,emptyValues=[undefined,null,false,0,'','0'];if(Object.prototype.toString.call(mixed_var)==='[object Array]'&&mixed_var.length===0){return true;}
for(i=0,len=emptyValues.length;i<len;i++){if(mixed_var===emptyValues[i]){return true;}}
if(typeof mixed_var==='object'){for(key in mixed_var){if(mixed_var.hasOwnProperty(key)){return false;}}
return true;}
return false;},parseQueryString:function(queryString){var params={},queries,temp,i,l;queries=queryString.split('&');for(i=0,l=queries.length;i<l;i++){temp=queries[i].split('=');params[temp[0]]=temp[1];}
return params;}};var spinImg=(Modernizr.cssanimations)?'<div class="spinner"><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div>':'<img src="'+ THEME_IMG_URI+'/ajax-loader.gif" alt="loading">';Site.infinitescroll=function(opts){var _this=this;this.link=(typeof opts.link==='string')?document.querySelector(opts.link):opts.link;this.appendTo=(typeof opts.appendTo==='string')?document.querySelector(opts.appendTo):opts.appendTo;this.success=(typeof opts.success==='function')?opts.success:function(){};this.ajaxurl=(typeof infinitescroll_vars==='object'&&typeof infinitescroll_vars.ajaxurl==='string')?infinitescroll_vars.ajaxurl:location.origin+'/wp-admin/admin-ajax.php';delete opts.link;delete opts.appendTo;delete opts.success;this.opts={action:'get_posts',paged:1};if(typeof opts.query_vars==='undefined'&&typeof infinitescroll_vars.query!=='undefined'){tempObj={};for(var key in infinitescroll_vars.query){if(!util.empty(infinitescroll_vars.query[key])){tempObj[key]=infinitescroll_vars.query[key];}}
this.opts=$.extend(this.opts,tempObj,opts);}
if(this.link){this.linktext=this.link.innerHTML;$(this.link).on('click',function(e){e.preventDefault();_this.link.innerHTML=spinImg;_this.opts.paged++;_this.load();});}};Site.infinitescroll.prototype={load:function(){var _this=this,xhr=new XMLHttpRequest();xhr.open('GET',this.ajaxurl+'?'+ util.getReqUri(this.opts));xhr.setRequestHeader('Accept','application/json');xhr.onreadystatechange=function(){if(this.readyState===4){var response=JSON.parse(this.responseText),postcount=response.posts.length,i;if(_this.appendTo){for(i=0;i<postcount;i++){_this.appendTo.insertAdjacentHTML('beforeend',response.posts[i].html);}}
if(response.next===true){if(_this.link.href.indexOf('?')===-1){_this.link.href=_this.link.href.replace(/\/page\/\d+\//g,'/page/'+(_this.opts.paged+ 1)+'/');}else{var hrefArr=_this.link.href.split('?');var params=util.parseQueryString(hrefArr[1]);params.paged=parseInt(params.paged,10)+ 1;_this.link.href=hrefArr[0]+'?'+ $.param(params);}}else{_this.link.style.display='none';}
_this.link.innerHTML=_this.linktext;_this.success(response);}};xhr.send();}};$(document).on('ready',function(){function equalHeight(group){group.each(function(i){if(i%2===0){var thisHeight=$(this).height();var nextItem=$(group[i+ 1]);var otherHeight=nextItem.height();var tallest=0;if(thisHeight>otherHeight){tallest=thisHeight;}else{tallest=otherHeight;}
$(this).height(tallest);nextItem.height(tallest);}});}
equalHeight($('.latest-infinite .article'));var $body=$('body');switch(true){case $body.hasClass('home'):Site.infinitescroll.instance=new Site.infinitescroll({link:'#main .infinitescroll a',appendTo:'#main .latest-infinite',templatePart:'posts-latest',success:function(){equalHeight($('.latest-infinite .article'));}});break;case $body.hasClass('author'):Site.infinitescroll.instance=new Site.infinitescroll({link:'#main .infinitescroll a',appendTo:'#main .latest-infinite',templatePart:'posts-latest',posts_per_page:5,success:function(){equalHeight($('.latest-infinite .article'));}});break;case $body.hasClass('tax-profile'):Site.infinitescroll.instance=new Site.infinitescroll({link:'#main .infinitescroll a',appendTo:'#main .articles',templatePart:'posts-taxonomy'});break;case $body.hasClass('page-template-taxonomy-php'):case $body.hasClass('archive'):case $body.hasClass('tag'):case $body.hasClass('search'):Site.infinitescroll.instance=new Site.infinitescroll({link:'#main .infinitescroll a',appendTo:'#main .launch-section',templatePart:'posts-taxonomy'});break;}});})(jQuery,Site);